version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/app/healthcheck", "8080", "api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      - PORT=8080
      - API_PATH=api/health
      # 如果需要调试，可取消下面这行的注释
      # - DEBUG=1
