version: '3.8'

services:
  healthcheck:
    image: debian
    container_name: healthcheck
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck", "8080", "api/health"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
