FROM rust:1.81-slim AS builder

WORKDIR /usr/src/app

# 下载健康检查工具并设置执行权限
RUN apt-get update && apt-get install -y wget && \
    wget -O /usr/src/app/api-server/healthcheck https://github.com/gptq/healthcheck/raw/refs/heads/main/bin/healthcheck-amd64 && \
    chmod +x /usr/src/app/api-server/healthcheck

# 使用Google distroless(noroot)版本作为最终镜像
FROM gcr.io/distroless/cc-debian12:nonroot

WORKDIR /app

# 复制编译好的二进制文件
COPY --from=builder /usr/src/app/api-server/target/release/aho-corasick-api /app/
# 复制健康检查工具
COPY --from=builder /usr/src/app/api-server/healthcheck /app/healthcheck